### PR TITLE
Fix search function

### PR DESCRIPTION
**Pull request by SamProkopchuk**
Branch for debugging and fixing search function.
Specifically the search functionality for DFS is flawed (can go back & forth/loop over 2 timesteps).

### CODE REVIEW

**Comment by richardye101** [comment]
I wonder if this is what Paco was talking about, how DFS should only be called every few time steps

**Comment by SamProkopchuk** [comment]
> I wonder if this is what Paco was talking about, how DFS should only be called every few time steps

When did he mention this? 
I also chatted with someone else in D84 this morning and they said they're encountering the same thing with DFs.

**Comment by SamProkopchuk** [comment]
Also an interesting test case to debug:
`./AI_search 127 1 1 1 0`

**Comment by richardye101** [comment]
image

**Comment by richardye101** [comment]
For [visit_order](https://github.com/richardye101/CSCD84-Artificial-Intelligence/blob/6e90203e175a3a71cdd0e2157fdf6c6305533858/Assignments/A1/Distro/AI_search.c#L493), [counting starts at 1](https://github.com/richardye101/CSCD84-Artificial-Intelligence/blob/6e90203e175a3a71cdd0e2157fdf6c6305533858/Assignments/A1/Distro/AI_search.c#L393-L398)

**Comment by richardye101** [comment]
When [checking for cats](https://github.com/richardye101/CSCD84-Artificial-Intelligence/blob/6e90203e175a3a71cdd0e2157fdf6c6305533858/Assignments/A1/Distro/AI_search.c#L516), i believe its a bug that you're checking against `cord` (the current node) rather than the `next_cord` (where the loop to check for a cat actually lies)

**Comment by richardye101** [comment]
When inserting into the data structure,

We should be pushing to the front in [Line 192](https://github.com/richardye101/CSCD84-Artificial-Intelligence/blob/6e90203e175a3a71cdd0e2157fdf6c6305533858/Assignments/A1/Distro/AI_search.c#L192) and [Line 196](https://github.com/richardye101/CSCD84-Artificial-Intelligence/blob/6e90203e175a3a71cdd0e2157fdf6c6305533858/Assignments/A1/Distro/AI_search.c#L196).

I think this was the issue, BFS seems to work well for me now.

**Comment by richardye101** [comment]
Min heap bubbles up the min priority node, but it doesnt bubble down the replaced node as in [line 145](https://github.com/richardye101/CSCD84-Artificial-Intelligence/blob/6e90203e175a3a71cdd0e2157fdf6c6305533858/Assignments/A1/Distro/AI_search.c#L145)

**Review by richardye101 — APPROVED** [review]
LGTM

**Pull request merged**
